### PR TITLE
fix(app): Show main nav notification dot for updatable connected robot

### LINKED ISSUE #2642: App Nav: Show notification dot on "Robots" if connected robot out of date
## overview

As a robot user, I would like the app to notify me at all times if my currently connected robot is out of date.

This ticket is a follow up to #806: q notification dot on "Robots" when _any_ robot update was available was a confusing experience and was removed. However, with no notification dot on the top level nav icon, it's harder for the user to know their robot is out of date once they leave the robots page. 

## current behavior

The top-level "Robots" nav button never has a notification dot.

## desired behavior

- [x] If the connected robot is out of date, "Robots" nav button should show a notification dot

### PR DESCRIPTION
**Pull request by Kadee80**
## overview

closes #2642

## changelog

- fix(app): Show main nav notification dot for updatable connected robot
- remove broken `getAnyRobotUpdateAvailable` selector and tests

## review requests
- open app
- [ ] App opens and no notification dot on robots tab

- connect to a robot with an available update
- [ ] robots tab displays notification dot

- navigate to upload or other page with a robot connected
- [ ] robots tab still displays notification dot

### CODE REVIEW

File: app/src/http-api-client/server.js [hunk 1]
```diff
@@ -308,6 +309,18 @@ export const makeGetRobotIgnoredUpdateRequest = () => {
...
 
+export function getConnectedRobotUpgradeAvailable (state: State) {
+  const connectedRobot = getConnectedRobot(state)
+  if (!connectedRobot) {
+    return false
+  }
+  const currentVersion = getRobotApiVersion(connectedRobot)
+  const updateVersion = getApiUpdateVersion(state)
+  const current = semver.valid(currentVersion)
+  const upgradeAvailable = current && semver.gt(updateVersion, current)
```
Comment (mcous) [inline app/src/http-api-client/server.js]: This logic is copied from another function in this same file, so I'd like to extract it to avoid the risk of drift. I haven't tested the following code but something along these lines will work I think

```js
// ...

export type RobotUpdateInfo = {version: string, type: RobotUpdateType}

const compareCurrentVersionToUpdate = (
  currentVersion: ?string,
  updateVersion: string
): RobotUpdateInfo => {
  const current = semver.valid(currentVersion)
  let type = null

  if (current && semver.gt(updateVersion, currentVersion)) {
    type = 'upgrade'
  } else if (current && semver.lt(updateVersion, currentVersion)) {
    type = 'downgrade'
  }

  return {version: updateVersion, type: type}
}

export const makeGetRobotUpdateInfo = () => {
  const selector: OutputSelector<State,
    AnyRobot,
    RobotUpdateInfo> = createSelector(
      (_, robot) => getRobotApiVersion(robot),
      getApiUpdateVersion,
      compareCurrentVersionToUpdate
    )

  return selector
}

// ...

export const getConnectedRobotUpgradeAvailable: OutputSelector<State,
  void,
  boolean> = createSelector(
    getConnectedRobot,
    getApiUpdateVersion,
    (robot, updateVersion) => {
      const currentVersion = robot && getRobotApiVersion(robot)
      const info = compareCurrentVersionToUpdate(currentVersion, updateVersion)
      return info.type === 'upgrade'
    }
  )
```
