### PR TITLE
fix(labware): Fix generator well y calculation, update docs/schema

### LINKED ISSUE #3602: Clean up & verify documentation for V2 Labware Definitions/Schema
## overview

I know of 2 places where v2 labware defs are documented (might be more I don't know about). The docs there are not quite right:

1. The `description`s in the schema. Some of those are wrong, eg for `z` in a well it says `Z location of center-top of well in reference to left-front-bottom of labware` whereas I think it's the distance from the bottom (not top) of a well to the bottom of the labware?

2. `labware-designer/README.md` is another source of labware v2 docs but they're missing details like for z again, it only says `Z-axis distance in **mm**`

## starting point

- Go thru all the `description`s in the schema and make sure they're complete and correct
- Update `labware-designer/README.md` and make sure its documentation of the v2 labware defs is complete & correct (BONUS: pictures/diagrams would be nice!). NOTE: "This example generates corning_96_wellplate_360ul_flat.json:" does NOT generate the right labware. As of this writing, that labware def isn't merged yet.
- Any other places to clean up?
- Any plans to document this on docs.opentrons.com (even just a link to the labware designer README)?

### PR DESCRIPTION
**Pull request by mcous**
## overview

In the process of updating the labware generator + schema descriptions to close #3602, I discovered: 

1. The well y-calculation of the generator was subtly incorrect
2. The schema wasn't properly checking values of the `wells` dictionary
 
For (1): the user input `offset` field to the generator is _supposed_ to be from the top-left of the labware to mirror labware dimensional drawings (as well as our upcoming labware creator UI). The generator, however, was treating this offset as from the bottom-left.

This worked for most labware (because symmetry!) and for non-symmetrical labware this difference was correcting by flipping the input or manually. To align the generator with the upcoming UI, I switched the generator to treat the input as its docs specify.

For (2): the pattern matcher for well names was incorrect.

I also fixed the docs and schema descriptions, so this PR closes #3602

## changelog

- Fix generator well y calculation
- Fix schema well checking
- Update labware generator docs and labware schema descriptions

## review requests

- [ ] My math is correct w.r.t. y-coordinate determination (specifically with flipping the coordinate system)
- [ ] Snapshot updates / fixture changes are sane
- [ ] Docs / schema descriptions look good

### CODE REVIEW

File: shared-data/js/labwareTools/index.js [hunk 1]
```diff
@@ -198,28 +220,28 @@ export function determineIrregularOrdering(
...
-      .reverse()
-      .forEach((element, rIndex) => {
-        wells[element] = {
-          ...well,
-          x: round(cIndex * spacing.column + offset.x, 2),
-          y: round(rIndex * spacing.row + offset.y, 2),
-          z: round(offset.z - well.depth, 2),
-        }
-      })
+    column.forEach((element, rIndex) => {
```
Comment (IanLondon) [inline shared-data/js/labwareTools/index.js]: - The comment about about `reverse()` and `slice()` is no longer relevant
- Mutating the accumulator of a `reduce` within the reducer's inner fn weirds me out
- Could `element` be called `wellName`?

File: shared-data/labware/schemas/2.json [hunk 2]
```diff
@@ -200,8 +200,9 @@
     "wells": {
       "type": "object",
       "description": "Unordered object of well objects with position and dimensional information",
+      "additionalProperties": false,
       "patternProperties": {
-        "['A' - 'Z'][*]": {
+        "[A-Z][0-9]+": {
```
Comment (IanLondon) [inline shared-data/labware/schemas/2.json]: nice catch thanks

Comment (IanLondon) [reply shared-data/labware/schemas/2.json]: actually could this be `[A-Z]+[0-9]+` to accommodate future labware with > 26 rows? Eg wells like `AA1`
