### PR TITLE
fix(protocol-designer): filters out non trash labware for blowout options

### LINKED ISSUE #4348: Protocol Designer: Blowout Destinations faulty options
## overview

When choosing a blowout destination,  I am given the option to select a well plate and even a tiprack instead of choosing traditional blowout destinations; "trash", "source well", or "destination well" .

Screen Shot 2019-10-31 at 11 29 32 AM

## current behavior

displayed options present tip racks and other labware as viable blowout destinations.

## steps to reproduce

Select blowout advanced option in a transfer step.

## expected behavior

Should only see the following options "Trash", "Source Well", "Destination Well".

### PR DESCRIPTION
**Pull request by shlokamin**
## overview
Filter out labware that is not a trash bin for blowout location options. Fixes #4348

## review requests

- Code review 
- Go [here](http://sandbox.designer.opentrons.com/blowout_destinations_faulty_options/), create/upload protocol with tipracks/well plates, select blowout advanced option in a transfer step,  only "trash", "source well", or "destination well" should appear as dropdown options

### CODE REVIEW

File: protocol-designer/src/ui/labware/selectors.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ import { selectors as labwareIngredSelectors } from '../../labware-ingred/select
 import type { Options } from '@opentrons/components'
 import type { Selector } from '../../types'
 import type { LabwareEntity } from '../../step-forms'
+import { getLabwareHasQuirk } from '../../../../shared-data/js/helpers'
```
Comment (mcous) [inline protocol-designer/src/ui/labware/selectors.js]: Can you reference shared-data by its package name instead? This comment applies to a few other places in this PR `@opentrons/shared-data`

File: protocol-designer/src/ui/labware/selectors.js [hunk 2]
```diff
@@ -52,18 +53,16 @@ export const getDisposalLabwareOptions: Selector<Options> = createSelector(
...
-        // Until then, allow all labware to be used for disposal
-        return [
-          ...acc,
-          {
-            name: names[labwareId],
-            value: labwareId,
-          },
-        ]
-      },
+      (acc: Options, labware: LabwareEntity, labwareId): Options =>
```
Comment (mcous) [inline protocol-designer/src/ui/labware/selectors.js]: Not introduced by this PR, so not change necessary, but it looks like this could've been a `flatMap` rather than a `reduce`

File: protocol-designer/src/ui/labware/test/selectors.test.js [hunk 3]
```diff
@@ -0,0 +1,59 @@
+import { getDisposalLabwareOptions } from '../selectors'
```
Comment (mcous) [inline protocol-designer/src/ui/labware/test/selectors.test.js]: Since this is a new directory + test, would you mind renaming this directory to `__tests__`? Both conventions (`test` and `__tests__`) exist in the repo, and one isn't technically better than the other, but I've been tending to prefer `__tests__` for newer code because:

- Our flow config ignore ignores all files in directories named `test` (for a reason that doesn't quite make sense, but is easier to explain in person), so if you want to write tests with typing, `__tests__` is better
- Jest default _directory_ matcher for tests is `__tests__`, so it's one less thing to make a decision about ([default jest test matcher](https://jestjs.io/docs/en/configuration#testregex-string--arraystring))

File: protocol-designer/src/ui/labware/test/selectors.test.js [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+import fixture_tiprack_1000_ul from '../../../../../shared-data/labware/fixtures/2/fixture_tiprack_1000_ul.json'
+import fixture_tiprack_10_ul from '../../../../../shared-data/labware/fixtures/2/fixture_tiprack_10_ul.json'
+import fixture_trash from '../../../../../shared-data/labware/fixtures/2/fixture_trash.json'
+
+jest.mock('../../../labware-defs/utils')
```
Comment (mcous) [inline protocol-designer/src/ui/labware/test/selectors.test.js]: I don't see this mock being used; is it to mock out the `require.context` stuff? If so, it might make sense to move this to our global mock setup in `<rooDir>/scripts`

File: protocol-designer/src/ui/labware/selectors.js (hunk 1 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: totally — does this get scoped by `package.json` in `shared-data`?

File: protocol-designer/src/ui/labware/selectors.js (hunk 2 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: sweet, ill give `flatMap` a go

File: protocol-designer/src/ui/labware/test/selectors.test.js (hunk 3 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/test/selectors.test.js]: thanks for the explanation! I agree that `__tests__` makes more sense. if this isn't already in the cookbook we should add it!

File: protocol-designer/src/ui/labware/test/selectors.test.js (hunk 4 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/test/selectors.test.js]: yeah it's used to mock out `require.context` (i guess it's webpack specific). But good suggestion, I'll move this to the global mock setup

File: protocol-designer/src/ui/labware/selectors.js (hunk 1 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: as per discussion, gets configured by the `main` field in `shared-data`'s `package.json` via yarn workspaces

File: protocol-designer/src/ui/labware/selectors.js (hunk 2 above)
Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: `labwareEntities` is a map, not a list, so I dont think `flatMap` will work :/

Comment (mcous) [reply protocol-designer/src/ui/labware/selectors.js]: Sorry, should've been more specific: meant `lodash/flatMap`. The flow definitions for lodash are pretty poor, though, so if we've got typing working with `lodash/reduce`, then it's probably best to leave this alone for now

Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: Yeah so I tried to implement this using `lodash/flatMap`, and i ran into a few issues:

1. Flow won't let me add a third parameter to the callback function (the key to the object)
2. When I iterate through the `names` object, I get the value back, not they key. So something like this won't work:

```
flatMap(names, name => {
  return getLabwareHasQuirk(labwareEntities[name].def, 'fixedTrash')
    ? [
        {
          name: name,
          value: labwareEntities[name].id,
        },
      ]
    : []
})
```
Because I actually need the key, which is the actual id of the labware in order to look it up in `labwareEntities`

Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: If I'm missing something and you see a cool way to do this lmk, I'm curious  🤔

Comment (mcous) [reply protocol-designer/src/ui/labware/selectors.js]: FFR, the lodash iterators have key as the second argument when used with objects:

```
/** Returns options for disposal (e.g. fixed trash and trash box) */
export const getDisposalLabwareOptions: Selector<Options> = createSelector(
  stepFormSelectors.getLabwareEntities,
  getLabwareNicknamesById,
  (labwareEntities, names) =>
    flatMap<LabwareEntities, DropdownOption>(
      labwareEntities,
      (labware: LabwareEntity, labwareId: string): Options =>
        getLabwareHasQuirk(labware.def, 'fixedTrash')
          ? [
              {
                name: names[labwareId],
                value: labwareId,
              },
            ]
          : []
    )
)
```

Comment (shlokamin) [reply protocol-designer/src/ui/labware/selectors.js]: Ah, I was being dumb and still had the accumulator as the first argument, which is why I was getting the error. I wanted two arguments, not three. Thanks @mcous!!
