### PR TITLE
fix(app): properly enable/disable robot update from file button

### LINKED ISSUE #5429: bug: Update robot from file is disabled if update-server is up but robot-server is down
# Overview

The `update-server` operates independently from the `robot-server` so that robots can continue to be updated if something goes wrong with the main application. If the app detects that the update-server is up, it is supposed to enable all robot update buttons in the app even if the main application server is down.

# Current behavior

If the `robot-server` is down, the "Update robot software from file" control in a robot's "Advanced Settings" menu is disabled even if the `update-server` is up and functioning.

# Steps to reproduce

1. Kill the `robot-server` on a RPi or OT-2
2. Go the the robot's advanced settings menu in the app
3. Notice that "Update robot software from file" is disabled

# Expected behavior

"Update robot software from file" should be enabled if the `update-server` is up

### PR DESCRIPTION
**Pull request by mcous**
# Overview

This PR tackles a few things that were blocking each other in the Robot Settings page UI. Primarily, it ensures:

- The robot autoupdate button displays the correct message and tooltip
    - Including switching the button text from "Up to date" to "Unavailable" if update files haven't been downloaded
- The update from file button actually gets enabled / disabled properly based on the update server health
    - Including tooltip if disabled
- The update from file button has been moved render in the Advanced Settings card _before_ the toggles rather than after the toggles
    - Moved with @pantslakz's agreement (see the bottom of this Slack thread: https://opentrons.slack.com/archives/C9GER57PC/p1599065069000300)
- The "robot out of date" modal won't trigger anymore if the update server isn't healthy

Fixes #5429

# Changelog

- Removed all usage of `<Card>`'s `disabled` prop
    - The prop is kinda buggy and also sets `pointer-events: none`
    - This bad for us because not all controls in a given card use the same disable logic as each other (e.g. in Advanced Settings, the toggles should be disabled if the api server is unhealthy, but update from file should be driven by the health of the update server)
    - This change picks away at #4391 
- Adds in some extra Card-child level disable logic to account for the parent component no longer caring about disable logic
- Moved robot update disable logic / messaging to a shared selector in the app's `buildroot` module

# Review requests

Note: using the local dev server is a good way to create a "bad update server" condition.

- [ ] Regular update button is disabled with tooltip if update-server is down
- [ ] Update from file button is disabled with tooltip if update-server is down
- [ ] All other Wi-Fi, Advanced Settings and Robot Controls buttons are disabled if **robot** server is down
    - A lot of these still don't have tooltips per #4391 

# Risk assessment

Hopefully pretty low, but since we're touching the update flow, a smoke test on a Buildroot robot update and a Balena robot migration couldn't hurt

### CODE REVIEW

File: app/src/buildroot/selectors.js [hunk 1]
```diff
@@ -87,29 +101,67 @@ export const getBuildrootRobot: State => ViewableRobot | null = createSelector(
   }
 )
 
-export function getBuildrootUpdateAvailable(
+export const getBuildrootUpdateAvailable: (
```
Comment (mcous) [inline app/src/buildroot/selectors.js:104]: Revert this change. It's a little risky and also the memoization is a bad idea given how this selector is used (with multiple robots at once)

**Comment by mcous** [comment]
Smoke tested...

✅ Regular upgrade via file
✅ Balena migration via file

...and everything went smoothly (read: as smoothly as expected when the lack of motor control hardware attached to a bare Pi will make the health endpoint 503 without config modification)

File: app/src/buildroot/selectors.js [hunk 2]
```diff
@@ -108,9 +119,60 @@ export function getBuildrootUpdateAvailable(
     }
   }
 
+  console.log(currentVersion, updateVersion, type)
```
Comment (mcous) [inline app/src/buildroot/selectors.js:122]: Damn.

File: app/src/buildroot/__tests__/selectors.test.js [hunk 3]
```diff
@@ -191,12 +223,107 @@ describe('buildroot selectors', () => {
...
+        autoUpdateDisabledReason: null,
+        updateFromFileDisabledReason: null,
+      },
+    },
   ]
 
   SPECS.forEach(spec => {
     const { name, selector, state, expected, setup } = spec
     const args = spec.args || []
-    if (typeof setup === 'function') setup()
```
Comment (mcous) [inline app/src/buildroot/__tests__/selectors.test.js:199]: Fun fact: mock setup wasn't working _at all_ in these tests...

File: app/src/buildroot/selectors.js [hunk 4]
```diff
@@ -14,6 +19,15 @@ import type {
   RobotSystemType,
 } from './types'
 
+// TODO(mc, 2020-08-02): i18n
+const UPDATE_SERVER_UNAVAILABLE =
+  "Unable to update because your robot's update server is not responding."
+const OTHER_ROBOT_UPDATING =
+  'Unable to update because the app is currently updating a different robot.'
+const NO_UPDATE_FILES =
+  'Unable to retrieve update for this robot. Ensure your computer is connected to the internet and try again later.'
```
Comment (sanni-t) [inline app/src/buildroot/selectors.js:28]: When does this happen?

**Review by sanni-t — APPROVED** [review]
Tested on my robot. Works as expected.
Just don't know how to test the case in the comment but looks like the unit test works so 👍

File: app/src/buildroot/selectors.js (hunk 4 above)
Comment (mcous) [reply app/src/buildroot/selectors.js:28]: Mainly this will happen in two cases:

- The user's computer is not connected to the internet
    - It's not able to check the `releases.json` manifest from S3 for the robot updates
    - #6494 makes this happen less often, so that it will only show up if the computer is not connected to the internet _and_ it has never been connected long enough to download the latest update
- The user has updated the latest version of the app but the robot update hasn't finished building / hasn't been uploaded to the release bucket
    - So in the 30 to 60 min window right when the app release is cut

File: app/src/buildroot/__tests__/selectors.test.js [hunk 5]
```diff
@@ -159,7 +191,7 @@ describe('buildroot selectors', () => {
       },
       expected: { name: 'robot-name', host: '10.10.0.0', port: 31950 },
       setup: () =>
-        getViewableRobots.mockReturnValueOnce([
+        getViewableRobots.mockReturnValue([
```
Comment (shlokamin) [inline app/src/buildroot/__tests__/selectors.test.js:194]: how come you switched `mockReturnValueOnce` to `mockReturnValue`?

File: app/src/buildroot/__tests__/selectors.test.js [hunk 6]
```diff
@@ -191,12 +223,107 @@ describe('buildroot selectors', () => {
...
+    },
+    {
+      name:
+        'getBuildrootUpdateDisplayInfo returns not allowed if another robot is updating',
+      selector: selectors.getBuildrootUpdateDisplayInfo,
+      state: { buildroot: { session: { robotName: 'other-robot-name' } } },
+      setup: () => {
+        getRobotByName.mockImplementation((state, name) => {
+          return { ...mockReachableRobot, name }
+        })
```
Comment (shlokamin) [inline app/src/buildroot/__tests__/selectors.test.js:270]: Why would we overwrite the `name` of the robot here? When I `console.log` the name that gets passed in to the mock, it's `undefined`.

Wouldn't we want to always just return the name of `mockReachableRobot`, which is different than `other-robot-name`? I.e.

```js
getRobotByName.mockReturnValueOnce(mockReachableRobot)
```

File: app/src/components/RobotSettings/UpdateFromFileControl.js [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+const UPDATE_FROM_FILE = 'Update robot software from file'
+const UPDATE_FROM_FILE_DESCRIPTION = (
+  <>
+    If your app is unable to auto-download robot updates, you can{' '}
+    <Link external href="https://www.opentrons.com/ot-app/">
+      download the robot update yourself
+    </Link>{' '}
+    and update your robot manually
+  </>
+)
```
Comment (shlokamin) [inline app/src/components/RobotSettings/UpdateFromFileControl.js:35]: Should descriptions like these go in `i18n`?

**Review by shlokamin — COMMENTED** [review]
Left a few questions, but tests are very thorough and code looks great

File: app/src/buildroot/__tests__/selectors.test.js (hunk 5 above)
Comment (mcous) [reply app/src/buildroot/__tests__/selectors.test.js:194]: I think `mockReturnValue` is more accurate to how the selectors would actually behave; a selector (if it chose to) might call some selector it is dependent multiple times with the same input, and you would expect the same output.

These tests weren't very well written (by me) with respect to mocks, so I've refactored to be more clear

File: app/src/buildroot/__tests__/selectors.test.js (hunk 6 above)
Comment (mcous) [reply app/src/buildroot/__tests__/selectors.test.js:270]: Oops, test was bad. Good catch!

File: app/src/components/RobotSettings/UpdateFromFileControl.js (hunk 7 above)
Comment (mcous) [reply app/src/components/RobotSettings/UpdateFromFileControl.js:35]: I think yes. Do you feel like I should put more than the TODO comment above given the app does not currently have an i18n system?

Comment (shlokamin) [reply app/src/components/RobotSettings/UpdateFromFileControl.js:35]: Ah missed the TODO comment. Do you know whether there are plans for the app to support i18n? If not, maybe @Opentrons/spddrs could consider taking this on as a longer term snacklog project we could pick at on Friday afternoons/during escalations or whatever. Or maybe we determine that it's just not worth it for the app to support i18n. Regardless, it's easy to keep kicking the can with this sort of stuff, and we should decide one way or another whether we'd like to commit to i18n or not.

File: app/src/buildroot/__tests__/selectors.test.js (hunk 3 above)
Comment (shlokamin) [reply app/src/buildroot/__tests__/selectors.test.js:199]: 🙃

File: app/src/components/RobotSettings/UpdateFromFileControl.js (hunk 7 above)
Comment (mcous) [reply app/src/components/RobotSettings/UpdateFromFileControl.js:35]: There are no plans that I'm aware of, but I think it's a great thing to tackle. There are a lot of `TODO... i18n` comments in the app's codebase

File: app/src/buildroot/__tests__/selectors.test.js [hunk 8]
```diff
@@ -1,202 +1,310 @@
...
+    const robot = { name: 'robot-name' }
+
+    getRobotApiVersion.mockReturnValue('1.0.1')
+
+    const result = selectors.getBuildrootUpdateAvailable(state, robot)
+
+    expect(result).toBe('downgrade')
+  })
+
+  it('should get update type when robot is matches the update', () => {
```
[the remark this answers is not in the document]
Comment (mcous) [reply app/src/buildroot/__tests__/selectors.test.js:97]: The update type is one of "upgrade", "downgrade", "reinstall", or `null`, but sure, can tweak the description

[the remark this answers is not in the document]
Comment (shlokamin) [reply app/src/buildroot/__tests__/selectors.test.js]: ohhh, I misunderstood what "update type" means in the description, I thought it meant "the update type of type upgrade", but that isn't the case here

**Review by shlokamin — APPROVED** [review]
LGTM!
