### PR TITLE
fix(protocol-designer): set magnetic module params for both pristine …

### LINKED ISSUE #4908: PD Bug: Pristine unsaved MAGNET form -> whitescreen
## overview

Problem with module ID field not being set in pristine unsaved magnet form when you close & open the form without saving. Whitescreen!

Note: this bug has not been released

## current behavior / steps to reproduce

1. Make a protocol with a magnetic module
2. Add a MAGNET step but don't save it
3. Click on another step eg Initial Deck Setup
4. Click on the MAGNET step again to select it
5. Click "Save" on the MAGNET step form

This causes a whitescreen. `TypeError: Cannot read property ‘moduleState’ of undefined` from `magnetUpdates.js:24`

## expected behavior

Module ID field should be correctly set in magnet steps, even when pristine + unsaved (and eventually, no "pristine unsaved" step forms allowed!)

### PR DESCRIPTION
**Pull request by shlokamin**
## overview

This PR closes #4908 by always setting magnetic module form params regardless of whether or not the form is pristine. 

Note: I did not add any test coverage. As per discussion with @IanLondon we plan to remove the non pristine form logic so I just simply added this patch for the time being. 

## review requests

- Make a protocol with a magnetic module
- Add a MAGNET step but don't save it
- Click on another step eg Initial Deck Setup
- Click on the MAGNET step again to select it
- [ ]  Click "Save" on the MAGNET step form, the step should have saved successfully

### CODE REVIEW

File: protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js [hunk 1]
```diff
@@ -82,6 +82,7 @@ export function getDefaultsForStepType(
       }
     case 'magnet':
       return {
+        moduleId: null,
```
Comment (shlokamin) [inline protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js]: Setting the default `null` module id isn't necessary for this ticket, but it makes it clear that a magnet step has a module id field (the same is done for temperature steps)

Comment (IanLondon) [reply protocol-designer/src/steplist/formLevel/getDefaultsForStepType.js]: good call
