### PR TITLE
fix(shared-data): fix irregular labware generator

### LINKED ISSUE #2781: Irregular labware definition generator flips ordering of wells
## overview

Recently, the 15_50mL tuberack definition has been created for the new geometry system. During testing, it was found that coordinates were flipped from expected. 

## current behavior

'A1' resulted in moving to well 'C1' and 'A3' resulted in moving to well 'B3'

## steps to reproduce
```
from opentrons import protocol_api, hardware_control, types
import asyncio
ctx = protocol_api.ProtocolContext()
l = asyncio.get_event_loop()
api = l.run_until_complete(hardware_control.API.build_hardware_controller(force=True))
ad = hardware_control.adapters.SynchronousAdapter(api)
ctx.connect(ad)
labware = ctx.load_labware_by_name('Opentrons_6x15_mL_4x50_mL_tuberack', SLOT)
pip = ctx.load_instrument(’p300_single’, types.Mount.LEFT (or right) )
pip.move_to(labware.wells()[0].top())
```

## expected behavior

Well should move to their correct location in the irregular labware definition generator

### PR DESCRIPTION
**Pull request by Laura-Danielle**
## overview
Closes #2781. During labware testing, it was discovered that row coordinates were reversed from what they should be. So entering well 'A1' would result in the pipette moving to well 'C1' instead.

## changelog

- Add reversed list of row index to create coordinate
- Fix failing tests
- Re-do 15_50 definition

Here are the parameters for reference:
```
metadata : {"displayName": "Opentrons 15x50mL tuberack", "displayCategory": "tuberack", "displayVolumeUnits": "mL", "displayLengthUnits": "mm", "tags": ["opentrons", "modular", "tuberack", "15", "mL", "50"]},

offset : [{x: 13.875, y: 17.75, z: 123.76}, {x: 71.375, y: 25.25, z: 119.8}],

grid : [{row: 3, column: 2}, {row: 2, column: 2}],

spacing : [{row: 25, column: 25}, {row: 35, column: 35}],

dimensions : {overallLength: 127.75, overallWidth: 85.5, overallHeight: 123.76},

well : [{totalLiquidVolume: 15, diameter: 14.5, shape: "circular", depth: 117.98}, {totalLiquidVolume: 50, diameter: 26.45, shape: "circular", depth: 113.85}],

gridStart : [{rowStart: 'A', colStart: '1', rowStride: 1, colStride: 1}, {rowStart: 'A', colStart: '3', rowStride: 1, colStride: 1}],

parameters = {format: "irregular", isTiprack: false, isMagneticModuleCompatible: false},

brand : {brand: "Opentrons"}
```

## review requests

Test on robot when you have a free moment

### CODE REVIEW

File: shared-data/js/labwareTools/index.js [hunk 1]
```diff
@@ -137,10 +137,11 @@ function determineLayout (
   wells: Array<Well>): {[wellName: string]: Well} {
   const wellMap = {}
   grids.forEach((gridObj, gridIdx) => {
+    const reverseRowIdx = range(gridObj.row, 0)
     range(gridObj.column).forEach(colIdx => {
       range(gridObj.row).forEach(rowIdx => {
```
Comment (IanLondon) [inline shared-data/js/labwareTools/index.js]: Could you reverse this range with the `range(gridObj.row, 0)` trick instead of making the `reverseRowIdx` array?

File: shared-data/definitions2/opentrons_6x15_mL_4x50_mL_tuberack.json [hunk 2]
```diff
@@ -46,10 +46,10 @@
...
-        "isTiprack": false,
         "format": "irregular",
-        "loadName": "opentrons_6x15_mL_4x50_mL_tuberack",
-        "isMagneticModuleCompatible": false
+        "isTiprack": false,
+        "isMagneticModuleCompatible": false,
+        "loadName": "opentrons_6x15_mL_4x50_mL_tuberack"
     },
     "wells": {
         "A1": {
```
Comment (IanLondon) [inline shared-data/definitions2/opentrons_6x15_mL_4x50_mL_tuberack.json]: before the `y` values of A1, B1, C1 were: 17.75, 42.75, 67.75. Now they are 92.75, 67.75, 42.75. Were they only reversed in order, or were they reversed in order plus their y-offset was in the wrong direction?

Comment (Laura-Danielle) [reply shared-data/definitions2/opentrons_6x15_mL_4x50_mL_tuberack.json]: I noticed this when I put the PR up, which is why I have it as blocked. Need to double check that the coordinates are still being added correctly.

File: shared-data/js/labwareTools/index.js (hunk 1 above)
Comment (Laura-Danielle) [reply shared-data/js/labwareTools/index.js]: Thought I replied to this before, but I still need the forward range for the row name so will need to separate arrays unfortunately. (Unless you can think of a better way ❓ )

Comment (IanLondon) [reply shared-data/js/labwareTools/index.js]: oh right I didn't realize the name goes in the forward direction, cool
