### PR TITLE
fix(protocol-designer): fix labware copy mirroring

### LINKED ISSUE #1616: PD Bugs: Copying labware mirrors labware instead of copying it
## expected behavior

Copying labware should create an independent labware instance that isn't changed when its copy changes (and the copy shouldn't change when its copyee(?) changes)

## steps to reproduce

* Create labware
* Copy that labware to a new slot
* Make changes to either labware's ingredients, notice the change reflected in the other labware too

### PR DESCRIPTION
**Pull request by IanLondon**
## overview

Closes #1616

## changelog

- fix labware copying - no mirroring of name or ingredients
- update old COPY_LABWARE-related tests (had entirely wrong state shape -- good case for keeping Flow in tests!)

## review requests

- [ ] Copying a labware with ingredient contents should copy the ingredients, but not mirror them (eg they show up, if you edit the clone parent or the clone child labware's ingredients, it doesn't affect the ingredients of the other labware)
- [ ] Copying a labware with no nickname should update its disambiguation number
- [ ] Steps using cloned labware should still work normally

### CODE REVIEW

File: protocol-designer/src/labware-ingred/reducers/index.js [hunk 1]
```diff
@@ -213,19 +224,12 @@ export const ingredLocations = handleActions({
     console.warn(`TODO: User tried to delete ingred group: ${groupId}. Deleting entire ingred group not supported yet`)
     return state
   },
-  COPY_LABWARE: (state: LocationsState, action: CopyLabware) => {
+  COPY_LABWARE: (state: LocationsState, action: CopyLabware): LocationsState => {
     const {fromContainer, toContainer} = action.payload
-    return reduce(state, (acc, ingredLocations: {[containerId: string]: Wells}, ingredId) => {
```
Comment (IanLondon) [inline protocol-designer/src/labware-ingred/reducers/index.js]: months ago, `LocationsState` used to be `state[ingredId][containerId][wellId].volume` and I never updated this reducer
