### PR TITLE
fix(app): Allow valid pipette+ model names for display images

### LINKED ISSUE #3340: Pipette+: App Should Correctly Display pipette images for new models
## overview
App should correctly display images for pipette+ models when they are attached to a robot.
The images used should be the same as the ones for the older models.

Show a generic multichannel image for attached multi-channel pipette+ and a generic single channel image for attached single channel pipette+

### PR DESCRIPTION
**Pull request by Laura-Danielle**
## overview
Closes #3340. Due to the format of the pipette+ model names, images were not automatically being displayed on the instruments card.

## changelog
- Change REGEX to determine which images propogate in Run App on `attached instruments card`

## review requests
@mcous I see that you made a note that volumes and channels should come from API, should that be the correct implementation here or is changing the expression sufficient?

### CODE REVIEW

File: app/src/components/InstrumentSettings/InstrumentInfo.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ type Props = {
 }
 
 // TODO(mc, 2018-03-30): volume and channels should come from the API
-const RE_CHANNELS = /p\d+_(single|multi)/
+const RE_CHANNELS = /p(\d+|\+\d+)_(single|multi)/
```
Comment (mcous) [inline app/src/components/InstrumentSettings/InstrumentInfo.js]: Given the TODO above, could we address the underlying problem rather than continue to rely on this regex?

```js
// ...
import { getPipetteModelSpecs } from '@opentrons/shared-data'
// ...

export default function PipetteInfo(props: Props) {
  const { mount, model, name, onChangeClick, showSettings } = props
  const label = LABEL_BY_MOUNT[mount]
  const pipette = model ? getPipetteModelSpecs(model) : null
  const channels = pipette?.channels
  // ...

  return (
    // ...
      <div className={styles.image}>
        {channels && (
          <InstrumentDiagram
            channels={channels}
            className={styles.pipette_diagram}
          />
        )}
      </div>
    // ...
  )
```
