### PR TITLE
fix(protocol-designer): Only show slot access warnings for Gen1 modules

### LINKED ISSUE #5309: bug: PD Gen2 modules still show 8-channel crash warning on deckmap
# Overview

Currently no crash warnings render in new file modal or file settings page when a GEN 8 channel is selected and a GEN2 Module is added to the deck. However, crash warnings still render on the deck map regardless of modules being GEN2

# Current behavior

GEN2 Modules still have 8-channel access warnings on the deck map.

# Steps to reproduce
- Make sure disable module restrictions FF is OFF
- Make a protocol with a GEN1 8-Channel Pipette
- Add a GEN2 magnetic module and a GEN2 temperature module
- View the starting deck state
- Slot 4 and Slot 6 still have crash warnings on the deck map

# Expected behavior

Adding GEN2 modules to the deck should not render any GEN1 8-Channel crash warnings on the deck map.

### PR DESCRIPTION
**Pull request by Kadee80**
## overview

This PR closes #5309 by disabling deckmap slot warnings for GEN2 Modules only

## changelog

- fix(protocol-designer): Only show slot access warnings for Gen1 modules

## review requests

Make sure disable module restrictions FF is OFF
Make a protocol with GEN1 modules and a GEN1 8-Channel Pipette
- [ ] 8-channel access warnings render in Slot 4 and Slot 6

Change the magnetic module to GEN2
- [ ] 8-channel access warnings render in Slot 6 only
- [ ] No warning in Slot 4

Change the temperature module to GEN2
- [ ] No warnings in any slots

## risk assessment

Slow. PD deckmap only

### CODE REVIEW

File: protocol-designer/src/components/DeckSetup/DeckSetup.js [hunk 1]
```diff
@@ -208,10 +208,16 @@ const DeckSetupContents = (props: ContentsProps) => {
   // NOTE: naively hard-coded to show warning north of slots 1 or 3 when occupied by any module
   let multichannelWarningSlots: Array<DeckDefSlot> = showGen1MultichannelCollisionWarnings
     ? compact([
-        (allModules.some(moduleOnDeck => moduleOnDeck.slot === '1') &&
+        (allModules.some(
+          moduleOnDeck =>
+            moduleOnDeck.slot === '1' && moduleOnDeck.model.includes('V1')
```
Comment (IanLondon) [inline protocol-designer/src/components/DeckSetup/DeckSetup.js]: we shouldn't use string matching b/c weird stuff might happen eg (silly example) `MAGNETIC_MODULE_V10` would be treated as a 1 here. I'd feel better with something like `const MODELS_WITH_GEN1_PIPETTE_COLLISIONS = [MAGNETIC_MODULE_V1, TEMPERATURE_MODULE_V1]` then `... && MODELS_WITH_GEN1_PIPETTE_COLLISIONS.includes(moduleOnDeck.model)` or something like that

Comment (Kadee80) [reply protocol-designer/src/components/DeckSetup/DeckSetup.js]: i hear that, will make the change now

Comment (IanLondon) [reply protocol-designer/src/components/DeckSetup/DeckSetup.js]: Oh I found we have such a const already! `MODULES_WITH_COLLISION_ISSUES` in `protocol-designer/src/constants.js`

```js
export const MODULES_WITH_COLLISION_ISSUES = [
  MAGNETIC_MODULE_V1,
  TEMPERATURE_MODULE_V1,
]
```

Comment (Kadee80) [reply protocol-designer/src/components/DeckSetup/DeckSetup.js]: ok i'll try that... pushed a simpler change
