### PR TITLE
fix(app): Show spinner during home on deck calibration exit

### LINKED ISSUE #1613: Show pipette moving + spinner overlay on deck calibration exit
## overview

When exiting deck calibration: it doesn’t have the same pipette moving + spinner overlay as when you start calibration. Because the exit modal just persisted after clicking exit I wasn’t sure if that was going right. 

## steps to reproduce

- [ ] Start deck calibration 
- [ ] Exit deck calibration

### PR DESCRIPTION
**Pull request by mcous**
## overview

This PR reorganizes the action chain on "Exit" click during deck calibration so that the homing spinner from #1726 gets shows during DC exit.

Closes #1613

## changelog

- fix(app): Show spinner during home on deck calibration exit 

## review requests

Required some tweaks in the bespoke action chaining util to handle the fact that the (now deprecated) react-router-redux middleware swallows route change actions rather than returning them, which goes against redux conventions and results in `dispatch(push(path))` returning `undefined` rather that the `push` object. Hurray.

- [ ] Deck calibration still works

Tested on Sunset and looks good to me

### CODE REVIEW

File: app/src/util.js [hunk 1]
```diff
@@ -19,7 +17,7 @@ export function delay (ms: number): Promise<void> {
 // error means: error in action, error in payload, or promise rejection
 // TODO(mc, 2018-06-11): This is a little too bespoke for my tastes. Explore
 //   npm for available ecosystem solutions soon
-export function chainActions (...actions: Array<Chainable>): ThunkChain {
+export function chainActions (...actions: Array<Chainable>): ThunkPromiseAction {
```
Comment (mcous) [inline app/src/util.js]: This change is a simplification / type fixup for chainActions. Previously, its return type would depend on its inputs. This seemed like a Pretty Bad Idea™, so now it always returns a Promise (even if the actions in the chain are not promises).

Since `chainActions` now returns one of our established action types, `dispatch`ing a action chain no longer trips up flow
