### PR TITLE
fix(protocol-designer): updates module slot placement after warning m…

### LINKED ISSUE #5383: bug: PD GEN2 => GEN1 switch does not update slot placement
# Overview

When switching from a GEN2 module to GEN1, the slot placement defaults back to slot 1 and is disabled but on save click, the slot is not updated.

# Current behavior

Morgans notes:

When I change module from GEN2 > GEN1 slot changes back to Slot 1 in this modal, which is correct. However in the File tab’s modules mini map and on the design tab’s deck map the slot is still Slot 9. 

When I click “edit” again the modal now also shows the module in Slot 9 and the dropdown is disabled so it cannot be moved to a supported slot without disabling module restrictions. 

# Steps to reproduce

Turn disable module restrictions OFF
Make a protocol with a GEN2 module
Choose a non default slot
Edit the module and change to GEN1 and observe slot placement dropdown behavior
Click save
Module Settings Card Slot and SlotMap will not have updated
Click edit again
Observe slot placement dropdown behavior

# Expected behavior

TBD after confirming with UX but our options are:

- When switching from GEN2 to GEN1 the slot placement dropdown is disabled, but retains the current slot

OR

- When switching from GEN2 to GEN1 the slot placement dropdown is disabled, defaults to supported slot, and clicking save updates the slot placement (if no errors)

### PR DESCRIPTION
**Pull request by shlokamin**
## overview

This PR closes #5383 by ensuring that the edit module form's save handler gets called from the blocking modal (if the user confirms). 

Note — I know this is ugly. I couldn't come up with another way around this because the logic is quite entangled. BUT I am currently also working on #5366 so I will be ripping this apart anyways. 

## review requests

- Turn disable module restrictions OFF
- Make a protocol with a GEN2 mag module
- Choose a non default slot
- Edit the module and change to GEN1
- Click save
- Confirm the blocking modal
- [ ] Make sure the minimap in the modal updates to the correct slot
- [ ] Make sure the deckmap in the design tab updates to the correct slot
- Click edit again
- [ ] Make sure you can edit the model/slot, and that the minimap + deckmap update accordingly

## risk assessment

Just PD

### CODE REVIEW

File: protocol-designer/src/components/modals/EditModulesModal/index.js [hunk 1]
```diff
@@ -104,25 +108,11 @@ export const EditModulesModal = (props: EditModulesProps) => {
...
-      onCloseClick()
-    },
-    content: <MagneticModuleWarningModalContent />,
-    enabled: enqueuedModuleModel != null,
-  })
 
-  const onSaveClick = (values: EditModulesState): void => {
+  const onSaveClick = (
+    values: EditModulesState,
+    skipBlockingModal: any
```
Comment (shlokamin) [inline protocol-designer/src/components/modals/EditModulesModal/index.js:114]: this sucks because the second argument when called from Formik is a `FormikBag` prop. So in essence I am overloading `onSaveClick` and calling it from outside of Formik, passing a second argument that is of type `boolean` instead of `FormikBag` to reuse logic. This is why I had to type it as `any`, which sucks and is dangerous.

Comment (shlokamin) [reply protocol-designer/src/components/modals/EditModulesModal/index.js:114]: see https://jaredpalmer.com/formik/docs/api/formik#onsubmit-values-values-formikbag-formikbag--void--promiseany
