### PR TITLE
ci(travis): run cypress e2e tests on build

### LINKED ISSUE #5318: CI: Run Cypress E2E tests in CI build
# Overview

We're got a bunch of E2E tests now. But we never run them! We should run Cypress tests in Travis.

NOTE: tests may be failing b/c we don't run them often. This ticket will be blocked by any test failures that come up.

### PR DESCRIPTION
**Pull request by IanLondon**
## overview

Run cypress tests in Travis! Build will fail if any e2e tests fail. Closes #5318 

This is dependent on #5424 - after it is merged, I'll rebase this PR and change `if (global.Cypress)` in that PR to `if (process.env.CYPRESS === '1')`.

## review requests

Sanity check!
- One weird thing I encountered was that labware library tests failed in Travis because GTM_ID env var was set, which somehow caused an error to be thrown about Intercom being undefined. So I set `GTM_ID=''` and also just to be safe I cut out the GTM tag from the Handlebars HTML template if GTM_ID is falsey.
- I'm using `wait-until` to make sure that the dev server is running before trying to start Cypress
- Cypress by default saves videos. I don't think they're useful to us, so I turned them off. We can always enable them and upload them to S3 if we decide that's good, but otherwise it just slows down the build.
- I didn't add any Make commands for running Cypress while you're writing tests. I kind of don't want to, I'd rather do `cd protocol-designer; yarn cypress open (whatever args)` rather than going thru Make.

## risk assessment

Significant risk to our workflow, but easy to roll back. If this causes builds to fail intermittently, or go too slowly, we'll have to change it back. Worst case scenario is removing `make test-e2e` from Travis yml to stop running the tests until we fix whatever problem we might have.

### CODE REVIEW

File: protocol-designer/src/components/FileSidebar/FileSidebar.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ const saveFile = (downloadData: $PropertyType<Props, 'downloadData'>) => {
   const blob = new Blob([JSON.stringify(downloadData.fileData)], {
     type: 'application/json',
   })
-  if (global.Cypress) {
+  if (process.env.CYPRESS === '1') {
```
Comment (dozercodes) [inline protocol-designer/src/components/FileSidebar/FileSidebar.js:46]: This will also have to be changed to an env var in your other PR #5424, right?

File: .travis.yml [hunk 2]
```diff
@@ -84,13 +84,14 @@ jobs:
 
     # test, build, and upload for JavaScript projects
     - stage: test
-      name: 'JS unit tests; build Protocol Designer, Labware Library, Components Library'
+      name: 'JS unit & E2E tests; build Protocol Designer, Labware Library, Components Library'
```
Comment (mcous) [inline .travis.yml:87]: I think it's a better idea to put E2E tests in their own parallel job in the test stage rather than blowing this job out even further.

If the reason it was placed in this stage was to prevent deploy of PD if the e2e tests don't pass, then I have two thoughts while we're still on Travis:

1. We could move PD deploy to a job in the "deploy" stage
    - This gates PD deploy on API tests passing
2. We could continue to put PD artifacts in S3 regardless of what the e2e tests say
    - PD "deploy" uploads artifacts in S3; it does not actually *deploy* anything
    - I don't think preventing artifact uploads on e2e failures is necessarily worth the effort (not that it's a bad idea or anything)

File: labware-library/Makefile [hunk 3]
```diff
@@ -34,6 +34,6 @@ serve: all
 # end to end tests
 .PHONY: test-e2e
 test-e2e:
-	concurrently --no-color --kill-others --success "first" --names "labware-library,labware-library-tests" \
-		"$(MAKE) dev" \
-		"cypress run --browser chrome"
+	concurrently --no-color --kill-others --success first --names "labware-library-server,labware-library-tests" \
+	"$(MAKE) dev CYPRESS=1 GTM_ID=''" \
```
Comment (mcous) [inline labware-library/Makefile:38]: Why are we defining a new environment variable? We already have NODE_ENV=test, I feel like it might be a little more straightforward to do NODE_ENV=cypress or e2e or something similar

File: protocol-designer/src/components/FileSidebar/FileSidebar.js [hunk 4]
```diff
@@ -43,7 +43,7 @@ const saveFile = (downloadData: $PropertyType<Props, 'downloadData'>) => {
...
     // HACK(IL, 2020-04-02): can't figure out a better way to do this yet
```
Comment (mcous) [inline protocol-designer/src/components/FileSidebar/FileSidebar.js:47]: Rather than polluting the application code here, could you replace `fileSaver` using `webpack` or `babel` if the environment doesn't support it? See https://github.com/eligrey/FileSaver.js/issues/501

Also, the app attached the Redux store to  the window if the NODE_ENV isn't production, but that doesn't feel like the problem here

Comment (IanLondon) [reply protocol-designer/src/components/FileSidebar/FileSidebar.js:47]: It will save fine under Cypress, but Cypress has no way to locate the file. Sometimes the test will timeout if a file is saved because depending on browser settings it might make a native "Save File..." modal that never closes, but that doesn't have to do with `fileSaver`

File: labware-library/Makefile (hunk 3 above)
Comment (IanLondon) [reply labware-library/Makefile:38]: It looks like we only ever set NODE_ENV to 'production' or 'development', I don't see `test`?

I was worried that since we're just using 2 states of NODE_ENV, we'd find places in our code with an assumption "if NODE_ENV isn't production then it must be development". But now going through uses of NODE_ENV the only time I see something like that is `const DEV_MODE = process.env.NODE_ENV !== 'production'` in app-shell which isn't going to cause an issue.

However, it's easy to do `if (NODE_ENV === 'development ) {/* dev stuff */} else {/* prod stuff, but oops this also happens when NODE_ENV is cypress */}` and IMO this is more complicated to think about than using a new env var.

Also any use of `process.env.CYPRESS` env var in the app code is an easy-to-search-for indicator that we had to do something gross to get Cypress to do something that it's not able to do, like looking at saved files

File: .travis.yml (hunk 2 above)
Comment (IanLondon) [reply .travis.yml:87]: >  don't think preventing artifact uploads on e2e failures is necessarily worth the effort (not that it's a bad idea or anything)

:+1:

File: labware-library/Makefile (hunk 3 above)
Comment (shlokamin) [reply labware-library/Makefile:38]: agree re:

> easy-to-search-for indicator

But I think we should be in the habit of explicitly checking strings rather than relying on an `else`

Comment (mcous) [reply labware-library/Makefile:38]: > It looks like we only ever set NODE_ENV to 'production' or 'development', I don't see test?

I don't much care, but since Jest sets NODE_ENV to `test` during testing, (see https://jestjs.io/docs/en/getting-started#using-babel; expand the "Making your Babel config jest-aware" section) I suggested `NODE_ENV="cypress"` to match that behavior. You can see our usage of this in our babel config:

```js
  env: {
    // Note(isk: 3/2/20): Must have babel-plugin-styled-components in each env,
    // see here for further details: s https://styled-components.com/docs/tooling#babel-plugin
    production: {
      plugins: ['babel-plugin-styled-components', 'babel-plugin-unassert'],
    },
    development: {
      plugins: ['babel-plugin-styled-components', 'react-hot-loader/babel'],
    },
    test: {
      plugins: [
        'babel-plugin-styled-components',
        '@babel/plugin-transform-modules-commonjs',
        'babel-plugin-dynamic-import-node',
      ],
    },
  },
```

> However, it's easy to do if (NODE_ENV === 'development' ) {/* dev stuff */} else {/* prod stuff, but oops this also happens when NODE_ENV is cypress */} and IMO this is more complicated to think about than using a new env var.

In my experience, checking for production environment should _always_ be checking that the env was explicitly set to production to avoid this exact issue.

File: .travis.yml [hunk 5]
```diff
@@ -84,7 +84,7 @@ jobs:
 
     # test, build, and upload for JavaScript projects
     - stage: test
-      name: 'JS unit tests; build Protocol Designer, Labware Library, Components Library'
+      name: 'JS unit; build Protocol Designer, Labware Library, Components Library'
```
Comment (mcous) [inline .travis.yml:87]: Unintentional removal of "tests"?

File: protocol-designer/src/components/FileSidebar/FileSidebar.js (hunk 4 above)
Comment (mcous) [reply protocol-designer/src/components/FileSidebar/FileSidebar.js:47]: Yeah to be clear, I'm not suggesting we change this `global.__lastSavedFile__ = downloadData.fileData` behavior during cypress runs. I'm saying that this override should happen using a mock for `FileSaver` that webpack (using the [resolve](https://webpack.js.org/configuration/resolve/) config or babel (using [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver))shims in when the environment is Cypress rather than putting the override logic in application code

Regardless, certainly not a request for this PR, sorry for not making clear in the original post

File: .travis.yml (hunk 5 above)
Comment (IanLondon) [reply .travis.yml:87]: d'oh
