### PR TITLE
fix(protocol-designer): add field level validation for magnetic module engage height

### LINKED ISSUE #5274: bug: engageHeight invalid values should make an error
# Overview

Entering just `-` or `.` in engageHeight in magnet step form is allowed, and shouldn't be

# Expected behavior

`-` and `.` should not be accepted as valid values for engageHeight field

### PR DESCRIPTION
**Pull request by shlokamin**
## overview
This PR closes #5274 by adding field level validation for magnetic module engage height text input. 

Along the way, I also refactored the `maskToFloat` input masker to just mask to float, and added an additional masker to trim decimals (previously `maskToFloat` was doing both) 

## changelog
refactor `maskToFloat` to just mask to float
change signature for `maskToInt`
add 'trimDecimals' masker
add field level validation for magnetic module engage height
## review requests
- code review 
- make sure you **CANNOT** submit non-numbered values into the `engage height` field

Because of the refactor I did, the following fields were affected, but shouldn't have changed. The expected behavior is that they should mask floats, and only allow one decimal place:

1. liquid placement form volume (when adding liquids to protocol)
2. aspirate air gap volume 
3. aspirate mix volume
4. dispense mix volume
5. multi dispense disposal volume (this one is tricky, PD won't let you multi-dispense if your volume is too big for the pipette to break up... see screenshot attached)
6. transfer volume field

image

## risk assessment

Medium — touches text input masking for several different forms in PD

### CODE REVIEW

**Comment by shlokamin** [comment]
Uh oh, aspirate volume also gets reset to 0 instead of clearing it entirely... looking into this now

**Comment by shlokamin** [comment]
Okay, so the issue was that one of the value limiters was replacing the entire string with "null" instead of empty string. Should be fixed now... thanks for catching this @Kadee80!

File: protocol-designer/src/steplist/fieldLevel/errors.js [hunk 1]
```diff
@@ -13,13 +13,15 @@ export type FieldError =
...
   | 'OVER_RANGE_MAXIMUM'
+  | 'NOT_A_REAL_NUMBER'
 
 const FIELD_ERRORS: { [FieldError]: string } = {
   REQUIRED: 'This field is required',
   UNDER_WELL_MINIMUM: 'or more wells are required',
   NON_ZERO: 'Must be greater than zero',
   UNDER_RANGE_MINIMUM: 'Min is',
   OVER_RANGE_MAXIMUM: 'Max is',
+  NOT_A_REAL_NUMBER: 'Must be a real number',
```
Comment (IanLondon) [inline protocol-designer/src/steplist/fieldLevel/errors.js:24]: since this may be exposed to the user, maybe "Must be a number"? They're not gonna put imaginary _`i`_ in there :stuck_out_tongue_closed_eyes:

Comment (shlokamin) [reply protocol-designer/src/steplist/fieldLevel/errors.js:24]: lol I am way too literal, will change
