### PR TITLE
PD: fix destination well pills in substeps

### LINKED ISSUE #1812: Distribute bug- some destination wells display as mixed
In a user test Piul was taking Ingredient 1 and distributing it into wells that had two states: empty or Ingredient 2. 

In the case where Ingredient 1 went into empty wells the side panel showed that Ingredient 1 was going into a well with Ingredient 1 in it. 

In the case where Ingredient 1 was going into wells with Ingredient 2, the side panel showed that Ingredient 1 was going into a well that already contained Ingredients 1 & 2. 

It seems to me like distribute was displaying the destination well state after the distribute, not their state before the distribute. 

---

It happened again in Cindy's usertest in two different ways:
image
image

### PR DESCRIPTION
**Pull request by IanLondon**
## overview

Closes #1812 and refactors `generateSubsteps` fn to lessen that fn's responsibilities. This bug was harder to see b/c `generateSubsteps` was managing timeline indicies, whereas now it's just fed the relevant timeline frames.

## changelog

    -calls to swatchColors use `Number` not `parseInt`, warns on non-integer input (NaNs)
    -clean up swatchColors import (no re-routing)
    
    -clarify names of labware/ingred types
    -rename 'substepId' to 'substepIndex' in PD substeps
    -less argument boilerplate in allSubsteps selector
    -remove namedIngredsByLabware selector, convert WellContents to NamedIngreds in getIngredsFactory fn instead
    -make generateSubsteps fn work on a single step, no longer is responsible
    for mapping across step list itself

## review requests

- See #1812 -- in substep Pills, do ingredients show up in the state of the beginning of that step (eg, matching what you see on the deck for this step and not the deck liquids on the **next** step?)
- Multi and single-channel substeps work

### CODE REVIEW

File: protocol-designer/src/steplist/generateSubsteps.js [hunk 1]
```diff
@@ -268,70 +258,51 @@ function commandToMultiRows (
...
 export function generateSubsteps (
-  validatedForms: {[StepIdType]: ValidFormAndErrors},
+  valForm: ?ValidFormAndErrors,
   allPipetteData: AllPipetteData,
-  allLabwareTypes: AllLabwareTypes,
-  namedIngredsByLabwareAllSteps: NamedIngredsByLabwareAllSteps,
-  orderedSteps: Array<StepIdType>,
-  robotStateTimeline: Timeline
-): SubSteps {
-  return mapValues(validatedForms, (valForm: ValidFormAndErrors, stepId: StepIdType) => {
```
Comment (IanLondon) [inline protocol-designer/src/steplist/generateSubsteps.js]: mapping across all the forms and using the stepId is now a responsibility of the `allSubsteps` selector, and not this `generateSubsteps` fn.

File: protocol-designer/src/top-selectors/well-contents/index.js [hunk 2]
```diff
@@ -105,27 +110,6 @@ export const lastValidWellContents: Selector<{[labwareId: string]: AllWellConten
   }
 )
 
-/** NamedIngred-formatted contents of wells, across all steps on the timeline */
```
Comment (IanLondon) [inline protocol-designer/src/top-selectors/well-contents/index.js]: :bomb: :boom:

File: protocol-designer/src/top-selectors/substeps.js [hunk 3]
```diff
@@ -1,31 +1,72 @@
...
-export const allSubsteps: Selector<{[StepIdType]: StepSubItemData | null}> = createSelector(
+const getIngredsFactory = (
+  wellContentsByLabware: WellContentsByLabware,
+  ingredNames: {[ingredId: string]: string}
+): GetIngreds => (labware, well) => {
+  const wellContents = (wellContentsByLabware &&
+    wellContentsByLabware[labware] &&
+    wellContentsByLabware[labware][well])
+
+  return wellContents.groupIds.map(id => ({
```
Comment (IanLondon) [inline protocol-designer/src/top-selectors/substeps.js]: `namedIngredsByLabware` selector replaced by this simpler mapping

File: protocol-designer/src/steplist/generateSubsteps.js [hunk 4]
```diff
@@ -230,7 +220,7 @@ function commandToMultiRows (
   command: AspDispCommandType,
   getIngreds: GetIngreds,
   getLabwareType: GetLabwareType,
-  channels: *
+  channels: 1 | 8
```
[the remark this answers is not in the document]
Comment (mcous) [reply protocol-designer/src/steplist/generateSubsteps.js]: We've got a few scattered about the codebase, including maybe one in `components`. But maybe we should just have a types lib or something?

File: protocol-designer/src/top-selectors/substeps.js [hunk 5]
```diff
@@ -1,31 +1,72 @@
...
+    allPipetteData,
+    allLabwareTypes,
+    ingredNames,
+    _allWellContentsForSteps,
+    orderedSteps,
+    robotStateTimeline
+  ) => {
+    return orderedSteps
+    .filter(stepId => stepId !== INITIAL_DECK_SETUP_ID) // TODO: Ian 2018-07-18 once deck setup step isn't in orderedSteps, this filter can be removed
+    .reduce((acc: AllSubsteps, stepId, timelineIndex) => {
```
Comment (mcous) [inline protocol-designer/src/top-selectors/substeps.js]: I _think_ this could work as a filter, map, and then reduce? (I'm just feeling clever this morning, this is not a change request):

```js
return orderedSteps
  .filter(stepId => stepId !== INITIAL_DECK_SETUP_ID) // TODO: Ian 2018-07-18 once deck setup step isn't in orderedSteps, this filter can be removed
  .map((stepId, timelineIndex) => {
    const robotState = robotStateTimeline.timeline[timelineIndex] &&
      robotStateTimeline.timeline[timelineIndex].robotState

    return {
      [stepId]: generateSubsteps(
        validatedForms[stepId],
        allPipetteData,
        (labwareId: string) => allLabwareTypes[labwareId],
        getIngredsFactory(_allWellContentsForSteps[timelineIndex], ingredNames),
        robotState,
        stepId
      )
    }
  })
  .reduce((acc: AllSubsteps, substepsById) => ({...acc, ...substepsById})
```

File: components/src/constants.js [hunk 6]
```diff
@@ -16,7 +16,9 @@ export const swatchColors = (n: number) => {
     '#2a97dc',
     '#d24193'
   ]
-  return colors[n % colors.length]
+  return (Number.isInteger(n))
```
[the remark this answers is not in the document]
Comment (IanLondon) [reply components/src/constants.js]: Yeah I'm not quite doing what I want here. The danger is that a malformed ingredient ID will be a `NaN`, and so `swatchColors` actually isn't guaranteed to return a string. I switched to just logging a warning, which made an upstream bug I didn't know about appear (a well that contains `'__air__'` and a single ingredient will appear mixed). I like these kinds of warnings to highlight hard-to-find bugs. When I have time I want to replace them with an assertions library like `assert` that can get stripped out for prod if we want it to be
