### PR TITLE
fix(protocol-designer): Hide CrashInfoBox when module restrictions disabled

### LINKED ISSUE #5276: bug: PD crash info warnings render in new file modal when in unrestricted mode
# Overview

This may be a regression or possibly solved by Gen2 module work at this time, but at the moment, if Module Restrictions are disabled, crash info warnings still render in new file modal.

# Current behavior

Crash info box renders in new file modal when module restrictions are disabled (FF on). This is not ideal since we can not render warnings/info for all possible crashes when you can place modules outside of the recommended slot.

Screen Shot 2020-03-24 at 11 25 36 AM
Screen Shot 2020-03-24 at 11 26 12 AM

# Steps to reproduce

- Go to settings
- Disabled module restrictions
- Create a new protocol with modules and a 8-Channel Gen1 pipette
- Crash info box and diagrams render

# Expected behavior

- Go to settings
- Disabled module restrictions
- Create a new protocol with modules and a 8-Channel Gen1 pipette
- No crash warnings should render in new file modal, file settings page, or deck

### PR DESCRIPTION
**Pull request by Kadee80**
## overview

closes #5276 by fixing a bug where crash info box was rendering when module restrictions were disabled.

## changelog

- fix(protocol-designer): Hide CrashInfoBox when module restrictions disabled
- refactor: Add test for hidden crash info box

## review requests

Make sure module restrictions FF is OFF
Make a protocol with a Gen1 Multi and a magnetic module
- [ ] Crash info box should render in new file modal
- [ ] Crash info box should render in file settings page

Make sure module restrictions FF is ON
Make a protocol with a Gen1 Multi and a magnetic module
- [ ] Crash info box should NOT render in new file modal
- [ ] Crash info box should NOT render in file settings page

## risk assessment

Low, should only affect PD new file modal, but please double check all crash info warnings render when they should in new file modal and file settings page.

### CODE REVIEW

File: protocol-designer/src/components/modals/FilePipettesModal/index.js [hunk 1]
```diff
@@ -366,7 +367,7 @@ export class FilePipettesModal extends React.Component<Props, State> {
                               />
                             </div>
                           )}
-                        {showCrashInfoBox && (
+                        {showCrashInfoBox && !moduleRestrictionsDisabled && (
                           <CrashInfoBox
```
Comment (shlokamin) [inline protocol-designer/src/components/modals/FilePipettesModal/index.js]: Can `!moduleRestrictionsDisabled` be added as part of `showCrashInfoBox`? Seems weird to check for `showCrashInfoBox`, check or something else, then render a component called `CrashInfoBox`
