### PR TITLE
fix(app): fix broken back-compat for pre-3.13.x robots

### LINKED ISSUE #4202: Protocol won't upload if robot and app versions are out of sync
## overview
This is an issue we began to see in 3.12.0. If the app is updated to 3.13 and the robot is still on 3.12, the protocol cannot be uploaded correctly and the app shows the following message:

Screen Shot 2019-10-10 at 11 43 39 AM

## expected behavior
There should be certain limitations if the app and the robot are out of sync, but should not affect user from uploading and running protocols on the robot.

### PR DESCRIPTION
**Pull request by IanLondon**
## overview

Closes #4202 

In #4099, I added a new argument to `Session.create` to support bundle execution, but missed the case where the App version was ahead of the robot server. This makes App backwards-compatible when calling `Session.create` via RPC.

## review requests

Push v3.12.0 on to a robot and check:
- [ ] Robot no longer raises error described in #4202 
- [ ] Protocols with errors should show the error as expected (and not swallow it)

- [ ] .py, .json, and bundle execution should still work the same when connected to robot server v3.13.1

### CODE REVIEW

File: app/src/robot/api-client/client.js [hunk 1]
```diff
@@ -152,13 +152,29 @@ export default function client(dispatch) {
...
+
     freshUpload = true
     remote.session_manager
       .create(name, contents, fileIsBinary(state.protocol.file))
-      .then(apiSession => {
-        remote.session_manager.session = apiSession
-        // state change will trigger a session notification, which will
-        // dispatch a successful sessionResponse
+      .then(updateSession)
+      .catch(error => {
```
Comment (mcous) [inline app/src/robot/api-client/client.js]: Should we hang this `catch` off `create`? That way we don't have to duplicate `.then(updateSession)`
