### PR TITLE
fix(protocol-designer): fix bug with timeline idx out of range

### LINKED ISSUE #3603: PD bug: with timeline errors present, substeps array index error -> whitescreen
## current behavior

Something's wrong with `getAllWellContentsForActiveItem`, causing a whitescreen bug when PD tries to render substeps downstream of a timeline error.

## steps to reproduce

Make a protocol that errors (eg delete tipracks until you run out of tips in some middle step) and mouseover any downstream StepItem. Whitescreen.

## expected behavior

Like in PD production, show no substeps for frames of the timeline that cannot be created due to upstream errors.

## dev notes

The line `const liquidState = timeline[timelineIdx].robotState.liquidState.labware` is what's failing, because `Uncaught TypeError: Cannot read property 'robotState' of undefined`. On examination, it's b/c `timelineIdx` is getting set to a number longer then the `timeline` array's length (via `timelineIdx = orderedStepIds.findIndex(id => id === activeItem.id)`).

The fix is probably going to be shorter than this ticket :grin:

### PR DESCRIPTION
**Pull request by IanLondon**
## overview

Closes #3603

## review requests

Check that bug reported in #3603 is fixed

### CODE REVIEW

File: protocol-designer/src/components/labware/SelectableLabware.js [hunk 1]
```diff
@@ -155,7 +155,7 @@ class SelectableLabware extends React.Component<Props> {
                 this.handleMouseEnterWell({ wellName, event })
                 makeHandleMouseEnterWell(
                   wellName,
-                  wellContents[wellName].ingreds
+                  wellContents[wellName]?.ingreds
```
Comment (IanLondon) [inline protocol-designer/src/components/labware/SelectableLabware.js]: When you mouse over a well in a step downstream of a timeline error, there are no wellContents for that labware because the timeline got truncated. This `?` here prevents a "TypeError: null has no property 'ingreds'" in that case.
