### PR TITLE
fix(protocol-designer): Update SlotMap and CrashInfoBox styles

### LINKED ISSUE #4989: PD: Modules file detail page edits
## Edit to mini-map responsiveness
image

Currently the mini map expands as the window gets wider. Can we limit the height to the height of the module photo on the left?

## Edit to mini-map viewport

If you look at the above picture the border lines are a bit thinner than the lines on the interior of the map. The display area needs to be expanded a bit so the full line width on the border can show. 

## Edit to the info icons
- [x] Flip the limited access slot ! so it becomes an i.  (I updated zeplin to reflect this). 
- [x] Change the info icon color in the mini map to match the icon color in the limited access to slots banner

### PR DESCRIPTION
**Pull request by Kadee80**
## overview

This PR closes #4989 by updating the viewbox for the slotmap to not crop the edge slot borders and matching crash warning icons on slotmap and crash info box in File Settings Page.

## changelog
- fix(protocol-designer): Update SlotMap and CrashInfoBox styles
- refactor(components): Add enzyme tests to SlotMap

## review requests
http://sandbox.designer.opentrons.com/pd_slot-map-edits/

- [ ] SlotMap borders all match
- [ ] SlotMap has max width on x-large screens
- [ ] Crash info Icons are both [i] in CrashInfoBox and Slotmap and color matches
- [ ] Tests are sane

### CODE REVIEW

File: components/src/slotmap/SlotMap.js [hunk 1]
```diff
@@ -29,7 +29,9 @@ const numCols = 3
 export function SlotMap(props: SlotMapProps) {
   const { collisionSlots, occupiedSlots, isError } = props
   return (
-    <svg viewBox={`0,0,${slotWidth * numCols}, ${slotHeight * numRows}`}>
+    <svg
+      viewBox={`-1,-1,${slotWidth * numCols + 2}, ${slotHeight * numRows + 2}`}
+    >
```
Comment (shlokamin) [inline components/src/slotmap/SlotMap.js]: I'm still getting the swing of things with these svg attributes, can you clarify what's going on here?

We are shifting the origin point of the svg one px to the left, and one px down. Then we are increasing the coordinate system's width and height by some amount too... It seems odd that we would need to shift the origin point, this must mean that the child rectangle is not centered, right? 

No need to hold this up, just wanted to understand this a bit more!

Comment (Kadee80) [reply components/src/slotmap/SlotMap.js]: We had to expand the viewbox a little so that the viewbox isn't cutting off a half pixel around the edge slot rectangles. Rather than going nuts with conditional pixel math for the slot grid we expanded the viewbox so there's a little 'air' around the SlotMap SVG itself
